apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-controller


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-controller
subjects:
  - kind: ServiceAccount
    name: vector-controller # name of your service account
    namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: vector-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "vector-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "vector-controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: vector-controller
      containers:
        - name: vector-controller
          image: {{ .Values.imageRegistry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9443
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs/
              name: tls-cert-vol
              readOnly: true
      volumes:
        - name: tls-cert-vol
          secret:
            defaultMode: 420
            secretName: vector-controller-admission

---

apiVersion: v1
kind: Service
metadata:
  name: vector-controller
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vector-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9443
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "vector-controller.selectorLabels" . | nindent 4 }}

